---
- name: install shipping component
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
    - name: install maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: prepare app directory
      ansible.builtin.file:
        path: /app
        state: "{{ item }}"
      loop: [absent, directory]

    - name: download and extract shipping
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /app
        remote_src: yes

    - name: build application
      ansible.builtin.command: "{{ item }}"
      args:
        chdir: /app
      loop:
        - mvn clean package
        - mv target/shipping-1.0.jar shipping.jar

    - name: copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    

    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: check and load schema
      block:
        - name: check if schema exists
          ansible.builtin.command: mysql -h 172.31.79.59 -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
          register: db

        - name: load sql files
          ansible.builtin.shell: "mysql -h 172.31.79.59 -uroot -p{{mysql_password}} < /app/db/{{ item }}.sql"
          loop: [app-user, schema, master-data]
          when: db.stdout == "0"

    - name: start shipping service
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes